AllCops:
  Excludes:
    - bin/**
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - db/schema.rb
