AllCops:
  Excludes:
    - bin/**
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - db/schema.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/AbcSize:
  Enabled: false